name: Combine JSON files in data directory

on:
  push:
    branches:
      - main
    paths:
      - 'Data/**'
  workflow_dispatch:

# VVVVVV این بخش را برای مدیریت اجراهای همزمان اضافه کنید VVVVVV
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
# ^^^^^^ پایان بخش اضافه شده ^^^^^^

jobs:
  combine-json:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      # 1. دانلود کد ریپازیتوری
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. نصب jq
      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      # 3. اجرای اسکریپت برای ترکیب فایل‌های JSON
      - name: Combine JSON files for each sub-directory
        run: |
          BASE_DIR="Data"
          if [ ! -d "$BASE_DIR" ]; then
            echo "Directory '$BASE_DIR' not found. Exiting."
            exit 0
          fi
          
          echo "Processing sub-directories in '$BASE_DIR'..."
          
          for dir in "$BASE_DIR"/*/; do
            if [ -d "$dir" ]; then
              subfolder_name=$(basename "$dir")
              echo "Processing sub-directory: $subfolder_name"
              output_file="$BASE_DIR/$subfolder_name.json"
              
              if ls "${dir}"*.json 1> /dev/null 2>&1; then
                jq -s '.' "${dir}"*.json > "$output_file"
                echo "Successfully created $output_file"
              else
                echo "No .json files found in $subfolder_name, skipping."
              fi
            fi
          done
          
          echo "JSON combination process finished."

      # 4. کامیت کردن فایل‌های جدید
      - name: Commit generated JSON files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "ci: auto-combine JSON files"
          file_pattern: "Data/*.json" 
          commit_user_name: "GitHub Actions"
          commit_user_email: "actions@github.com"
          commit_author: "GitHub Actions <actions@github.com>"
